name: GloPvP
version: 1.0.0
description: A kit plugin made for thejust219.
load: POSTWORLD
authors:
  - Steffion
#website: http://
main: nl.Steffion.GloPvP.GloPvP
database: false
#depend: [OnePlugin, AnotherPlugin]
#softdepend: [OnePlugin, AnotherPlugin]
#loadbefore: [OnePlugin, AnotherPlugin]